name: Sync fork with upstream

on:
  schedule:
    - cron: "0 8 * * *" # Runs every day at 8 AM GMT
  workflow_dispatch:

jobs:
  update_fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/microsoft/vscode.git

      - name: Fetch upstream changes
        run: |
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout -b update-from-upstream
          git merge upstream/main

      - name: Push changes to fork
        run: |
          git push -u origin update-from-upstream

      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --base main --head update-from-upstream --title "Update from upstream" --body "This pull request updates the fork with the latest changes from the upstream repository."
